"use client";
import{useEffect,useRef,useState}from"react";
type Day={date:string;parent:"Mathieu"|"Elana";location:string;dropoff:string;pickup:string};
const iso=(d:Date)=>d.toISOString().slice(0,10),add=(d:Date,n:number)=>{const x=new Date(d);x.setUTCDate(x.getUTCDate()+n);return x};
const personClass=(name:string)=>name==="Mathieu"?"mathieu":name==="Elana"?"elana":name==="—"?"none":"other";
export default function Agenda(){
const[start,setStart]=useState(new Date("2026-08-17T12:00:00Z")),[view,setView]=useState<7|14|35>(35),[days,setDays]=useState<Day[]>([]),[people,setPeople]=useState<string[]>([]),[locations,setLocations]=useState<string[]>([]),[selected,setSelected]=useState<number[]>([]),[selecting,setSelecting]=useState(false),[panel,setPanel]=useState(false),[manage,setManage]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),timer=useRef<ReturnType<typeof setTimeout>|null>(null),anchor=useRef<number|null>(null),longPressed=useRef(false);
const load=(resetSelection=true)=>{setLoading(true);setError("");return fetch(`/api/rafa-agenda?from=${iso(start)}&to=${iso(add(start,view-1))}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error(r.status===401?"Session expired. Please reload and enter the password again.":"Calendar could not load.");return r.json()}).then(x=>{setDays(x.days??[]);setPeople(x.people??[]);setLocations(x.locations??[]);setLoading(false);if(resetSelection)setSelected([])}).catch(e=>{setError(e.message);setLoading(false)})};
useEffect(()=>{void load()},[start,view]);
const begin=(i:number)=>{longPressed.current=false;timer.current=setTimeout(()=>{longPressed.current=true;anchor.current=i;setSelecting(true);setSelected([i]);navigator.vibrate?.(25)},450)},cancel=()=>{if(timer.current)clearTimeout(timer.current)},tap=(i:number,shiftKey:boolean)=>{cancel();if(longPressed.current){longPressed.current=false;return}if(shiftKey&&anchor.current!==null){const lo=Math.min(anchor.current,i),hi=Math.max(anchor.current,i);setSelecting(true);setSelected(Array.from({length:hi-lo+1},(_,n)=>lo+n));setPanel(false)}else if(selecting)setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i]);else{anchor.current=i;setSelected([i]);setPanel(true)}};
async function update(field:string,value:string){const dates=selected.map(i=>days[i].date);const r=await fetch("/api/rafa-agenda",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({dates,field,value})});if(!r.ok){alert("Update failed. Please try again.");return}await load(false)}
async function updateOne(date:string,field:string,value:string){const r=await fetch("/api/rafa-agenda",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({dates:[date],field,value})});if(!r.ok){alert("Update failed. Please try again.");return}const key=field==="place"?"location":field==="pick"?"pickup":"dropoff";setDays(ds=>ds.map(d=>d.date===date?{...d,[key]:value}:d))}
async function option(type:"person"|"location",action:"add"|"rename"|"remove",name:string,oldName?:string){const r=await fetch("/api/rafa-agenda",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,action,name,oldName})}),x=await r.json();if(!r.ok){alert(x.error??"Could not update");return}load()}
function addOption(type:"person"|"location"){const name=prompt(type==="person"?"Name of pickup/drop-off person":"Name of place");if(name?.trim())option(type,"add",name)}
function editOption(type:"person"|"location",oldName:string){const name=prompt("Edit name",oldName);if(name?.trim()&&name!==oldName)option(type,"rename",name,oldName)}
function removeOption(type:"person"|"location",name:string){if(confirm(`Remove “${name}” from future choices? Existing calendar entries will remain.`))option(type,"remove",name)}
return <main className="rafaApp"><header><div><b>Rafa’s agenda</b><span>Mathieu & Elana</span></div><div className="headerActions"><button onClick={()=>setManage(true)}>Manage Who & Where</button><select value={view} onChange={e=>setView(Number(e.target.value)as 7|14|35)}><option value="7">Week</option><option value="14">2 weeks</option><option value="35">Month</option></select></div></header>
<section className="rafaToolbar"><button onClick={()=>setStart(add(start,-view))}>‹</button><div><h1>{start.toLocaleString("en",{month:"long",year:"numeric",timeZone:"UTC"})}</h1><p>Long-press a day to select several</p></div><button onClick={()=>setStart(add(start,view))}>›</button></section>
{loading?<div className="rafaLoading">Loading…</div>:error?<div className="rafaLoading">{error}</div>:<div className={`rafaGrid v${view}`}>{days.map((d,i)=>{const dt=new Date(d.date+"T12:00:00Z");return <article key={d.date} role="button" tabIndex={0} className={`rafaDay ${d.parent==="Mathieu"?"dad":"mom"} ${d.date<iso(new Date())?"past":""} ${selected.includes(i)?"chosen":""}`} onPointerDown={()=>begin(i)} onPointerUp={cancel} onClick={e=>tap(i,e.shiftKey)} onPointerCancel={cancel} onContextMenu={e=>e.preventDefault()}><div className="date"><span>{dt.toLocaleString("en",{weekday:"short",timeZone:"UTC"})}</span><b>{dt.getUTCDate()}</b></div><div className="with"><small>RAFA IS WITH</small><strong>{d.parent}</strong></div><label className="inlineField where"><small>WHERE</small><select aria-label={`Where on ${d.date}`} value={d.location} onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()} onChange={e=>updateOne(d.date,"place",e.target.value)}>{!locations.includes(d.location)&&<option>{d.location}</option>}{locations.map(x=><option key={x}>{x}</option>)}</select></label><div className="transfers"><label className="inlineField"><small>PICK-UP BY</small><select aria-label={`Pickup on ${d.date}`} className={`personSelect ${personClass(d.pickup)}`} value={d.pickup} onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()} onChange={e=>updateOne(d.date,"pick",e.target.value)}>{!people.includes(d.pickup)&&d.pickup!=="—"&&<option>{d.pickup}</option>}{people.map(x=><option key={x}>{x}</option>)}<option>—</option></select></label><label className="inlineField"><small>DROP-OFF BY</small><select aria-label={`Drop-off on ${d.date}`} className={`personSelect ${personClass(d.dropoff)}`} value={d.dropoff} onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()} onChange={e=>updateOne(d.date,"drop",e.target.value)}>{!people.includes(d.dropoff)&&d.dropoff!=="—"&&<option>{d.dropoff}</option>}{people.map(x=><option key={x}>{x}</option>)}<option>—</option></select></label></div></article>})}</div>}
{selected.length>0&&<div className="rafaBulk"><b>{selected.length} selected</b><button onClick={()=>setPanel(true)}>Bulk update</button><button onClick={()=>{setSelected([]);setSelecting(false)}}>Clear</button></div>}
{panel&&<div className="rafaSheet"><button className="x" onClick={()=>setPanel(false)}>×</button><h2>Update {selected.length} day{selected.length>1?"s":""}</h2><label>Rafa is with<select defaultValue="" onChange={e=>update("with",e.target.value)}><option value="" disabled>Choose…</option><option>Mathieu</option><option>Elana</option></select></label><label>Where<select defaultValue="" onChange={e=>update("place",e.target.value)}><option value="" disabled>Choose…</option>{locations.map(x=><option key={x}>{x}</option>)}</select></label><label>Pickup by<select defaultValue="" onChange={e=>update("pick",e.target.value)}><option value="" disabled>Choose…</option>{people.map(x=><option key={x}>{x}</option>)}<option>—</option></select></label><label>Drop-off by<select defaultValue="" onChange={e=>update("drop",e.target.value)}><option value="" disabled>Choose…</option>{people.map(x=><option key={x}>{x}</option>)}<option>—</option></select></label><button className="done" onClick={()=>{setPanel(false);setSelecting(false)}}>Done</button></div>}
{manage&&<div className="rafaSheet manageSheet"><button className="x" onClick={()=>setManage(false)}>×</button><h2>Manage Who & Where</h2><section><div className="manageTitle"><h3>Who</h3><button onClick={()=>addOption("person")}>+ Add person</button></div><p className="hint">Used for drop-off and pickup.</p>{people.map(x=><div className="optionRow" key={x}><span className={`personTag ${personClass(x)}`}>{x}</span><div>{!["Mathieu","Elana"].includes(x)&&<><button onClick={()=>editOption("person",x)}>Edit</button><button className="remove" onClick={()=>removeOption("person",x)}>Remove</button></>}</div></div>)}</section><section><div className="manageTitle"><h3>Where</h3><button onClick={()=>addOption("location")}>+ Add place</button></div>{locations.map(x=><div className="optionRow" key={x}><span>{x}</span><div><button onClick={()=>editOption("location",x)}>Edit</button><button className="remove" onClick={()=>removeOption("location",x)}>Remove</button></div></div>)}</section><button className="done" onClick={()=>setManage(false)}>Done</button></div>}</main>}
