"use client";
import{useEffect,useRef,useState}from"react";
type Day={date:string;parent:"Mathieu"|"Elana";location:string;dropoff:string;pickup:string};
const iso=(d:Date)=>d.toISOString().slice(0,10),add=(d:Date,n:number)=>{const x=new Date(d);x.setUTCDate(x.getUTCDate()+n);return x};
export default function Agenda(){const[start,setStart]=useState(new Date("2026-08-18T12:00:00Z")),[view,setView]=useState<7|14|35>(7),[days,setDays]=useState<Day[]>([]),[selected,setSelected]=useState<number[]>([]),[selecting,setSelecting]=useState(false),[panel,setPanel]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
useEffect(()=>{setLoading(true);setError("");fetch(`/api/rafa-agenda?from=${iso(start)}&to=${iso(add(start,view-1))}`).then(async r=>{if(!r.ok)throw new Error(r.status===401?"Session expired. Please reload and enter the password again.":"Calendar could not load.");return r.json()}).then(x=>{setDays(x.days??[]);setLoading(false);setSelected([])}).catch(e=>{setError(e.message);setLoading(false)})},[start,view]);
const begin=(i:number)=>{timer.current=setTimeout(()=>{setSelecting(true);setSelected([i]);navigator.vibrate?.(25)},450)},cancel=()=>{if(timer.current)clearTimeout(timer.current)},touch=(i:number)=>{if(selecting)setSelected(s=>s.includes(i)?s:[...s,i])},tap=(i:number)=>{cancel();if(selecting)setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i]);else{setSelected([i]);setPanel(true)}};
async function update(field:string,value:string){const dates=selected.map(i=>days[i].date);await fetch("/api/rafa-agenda",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({dates,field,value})});const key=field==="with"?"parent":field==="place"?"location":field==="drop"?"dropoff":"pickup";setDays(ds=>ds.map((d,i)=>selected.includes(i)?{...d,[key]:value}:d));}
return <main className="rafaApp"><header><div><b>Rafa’s agenda</b><span>Mathieu & Elana</span></div><select value={view} onChange={e=>setView(Number(e.target.value)as 7|14|35)}><option value="7">Week</option><option value="14">2 weeks</option><option value="35">Month</option></select></header><section className="rafaToolbar"><button onClick={()=>setStart(add(start,-view))}>‹</button><div><h1>{start.toLocaleString("en",{month:"long",year:"numeric",timeZone:"UTC"})}</h1><p>Long-press a day to select several</p></div><button onClick={()=>setStart(add(start,view))}>›</button></section>{loading?<div className="rafaLoading">Loading…</div>:error?<div className="rafaLoading">{error}</div>:<div className={`rafaGrid v${view}`}>{days.map((d,i)=>{const dt=new Date(d.date+"T12:00:00Z");return <button key={d.date} className={`rafaDay ${d.parent==="Mathieu"?"dad":"mom"} ${selected.includes(i)?"chosen":""}`} onPointerDown={()=>begin(i)} onPointerUp={()=>tap(i)} onPointerEnter={()=>touch(i)} onPointerCancel={cancel} onContextMenu={e=>e.preventDefault()}><div className="date"><span>{dt.toLocaleString("en",{weekday:"short",timeZone:"UTC"})}</span><b>{dt.getUTCDate()}</b></div><div className="with"><small>RAFA IS WITH</small><strong>{d.parent}</strong></div><p><small>WHERE</small>{d.location}</p><p><small>DROP-OFF</small>{d.dropoff}</p><p><small>PICKUP</small>{d.pickup}</p></button>})}</div>}{selected.length>0&&<div className="rafaBulk"><b>{selected.length} selected</b><button onClick={()=>setPanel(true)}>Bulk update</button><button onClick={()=>{setSelected([]);setSelecting(false)}}>Clear</button></div>}{panel&&<div className="rafaSheet"><button className="x" onClick={()=>setPanel(false)}>×</button><h2>Update {selected.length} day{selected.length>1?"s":""}</h2><label>Rafa is with<select defaultValue="" onChange={e=>update("with",e.target.value)}><option value="" disabled>Choose…</option><option>Mathieu</option><option>Elana</option></select></label><label>Where<select defaultValue="" onChange={e=>update("place",e.target.value)}><option value="" disabled>Choose…</option><option>School / childcare</option><option>Mathieu’s home</option><option>Elana’s home</option><option>Holiday in France</option><option>Holiday in Florida</option></select></label><label>Drop-off<select defaultValue="" onChange={e=>update("drop",e.target.value)}><option value="" disabled>Choose…</option><option>Mathieu</option><option>Elana</option><option>—</option></select></label><label>Pickup<select defaultValue="" onChange={e=>update("pick",e.target.value)}><option value="" disabled>Choose…</option><option>Mathieu</option><option>Elana</option><option>—</option></select></label><button className="done" onClick={()=>{setPanel(false);setSelecting(false)}}>Done</button></div>}</main>}
